name: noisemap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - pyarrow
  - requests
  - tqdm
  - geopandas
  - shapely
  - pyproj          
  - scikit-learn
  - pytorch
  - torchvision     
  - pytorch-cuda=12.1
  - pip:
    - wandb
    - earthengine-api
    - aef-loader
    - odc-geo
    - nest-asyncio
    - geemap        # Added this for your GEE-to-XGBoost workflow